In [2]:
x=[115.3, 195.5, 120.5, 110.2, 90.4, 105.6, 110.9, 116.3, 122.3, 125.4,90.4]

In [3]:
mean = sum(x) / len(x)

In [4]:
mean

118.43636363636365

In [5]:
import statistics

In [6]:
print(statistics.mean(x))

118.43636363636364


In [7]:
x.sort()

In [8]:
x

[90.4, 90.4, 105.6, 110.2, 110.9, 115.3, 116.3, 120.5, 122.3, 125.4, 195.5]

In [9]:
n=len(x)

In [10]:
if  n% 2 == 0:
    median1 = x[n//2]
    median2 = x[n//2 - 1]
    median = (median1 + median2)/2
else:
    median = x[n//2]
print("Median is: " + str(median))

Median is: 115.3


In [11]:
print(statistics.median(x))

115.3


In [12]:
frequency = {}
for value in x:
        frequency[value] = frequency.get(value, 0) + 1

In [13]:
frequency

{90.4: 2,
 105.6: 1,
 110.2: 1,
 110.9: 1,
 115.3: 1,
 116.3: 1,
 120.5: 1,
 122.3: 1,
 125.4: 1,
 195.5: 1}

In [14]:
frequencs=list(frequency.values())
print(frequencs)

[2, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [15]:
most_frequent = max(frequencs)

In [16]:
most_frequent

2

In [17]:
modes = [key for key, value in frequency.items()
                      if value == most_frequent]

In [18]:
modes

[90.4]

In [19]:
print(statistics.mode(x))

90.4


In [20]:
variance = sum((i - mean) ** 2 for i in x) / (n-1)

In [21]:
variance

788.2365454545454

In [22]:
print(statistics.variance(x))

788.2365454545454


In [23]:
standarddev= variance ** 0.5

In [24]:
standarddev

28.07555067054866

In [25]:
print(statistics.stdev(x))

28.07555067054866


In [26]:
import numpy as np
max = np.max(x)
min = np.min(x)


In [27]:
scaled_arr = np.array([(i - min) / (max - min) for i in x])

In [28]:
print(scaled_arr)

[0.         0.         0.14462417 0.18839201 0.19505233 0.23691722
 0.24643197 0.28639391 0.30352046 0.33301618 1.        ]


In [29]:
x=[[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [30]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(x)
print(scaled)

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [41]:
X=[115.3, 195.5, 120.5, 110.2, 90.4, 105.6, 110.9, 116.3, 122.3, 125.4,90.4]
for i in range(len(X)):
        X[i] = (X[i] - statistics.mean(X)) /(statistics.stdev(X))

In [47]:
X=[115.3, 195.5, 120.5, 110.2, 90.4, 105.6, 110.9, 116.3, 122.3, 125.4,90.4]

In [48]:
stand_arr = np.array([(i -statistics.mean(X) ) / (statistics.stdev(X)) for i in X])

In [50]:
stand_arr

array([-0.11171156,  2.74486642,  0.07350297, -0.29336428, -0.99860423,
       -0.4572079 , -0.26843155, -0.07609338,  0.13761569,  0.24803205,
       -0.99860423])

In [53]:
print(round(statistics.mean(stand_arr),2))

-0.0


In [33]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler
# define data
data = asarray([[100, 0.001],
[8, 0.05],
[50, 0.005],
[88, 0.07],
[4, 0.1]])
print(data)
# define standard scaler
scaler = StandardScaler()
# transform 

scaled = scaler.fit_transform(data)
print(scaled)

[[1.0e+02 1.0e-03]
 [8.0e+00 5.0e-02]
 [5.0e+01 5.0e-03]
 [8.8e+01 7.0e-02]
 [4.0e+00 1.0e-01]]
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]


In [36]:
print(round(np.mean(scaled),5))

-0.0


In [35]:
print(np.std(scaled))

1.0
