In [52]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import GridSearchCV

In [53]:
df=pd.read_csv('glass.csv')
df.head(5)

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [54]:
x=df.drop(columns=['Type'])
y=df['Type']

In [55]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=8,test_size=0.30)

In [56]:
model=SVC(kernel='linear')
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)

In [57]:
print(accuracy_score(ytest,ypred))
print(classification_report(ytest,ypred))
print(confusion_matrix(ytest,ypred))

0.9846153846153847
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        20
           2       1.00      0.96      0.98        23
           3       0.86      1.00      0.92         6
           5       1.00      1.00      1.00         5
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         9

    accuracy                           0.98        65
   macro avg       0.98      0.99      0.98        65
weighted avg       0.99      0.98      0.99        65

[[20  0  0  0  0  0]
 [ 0 22  1  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  9]]


In [58]:
model1=SVC(kernel='rbf').fit(xtrain,ytrain)
model2=SVC(kernel='poly',degree=3).fit(xtrain,ytrain)
model3=SVC(kernel='sigmoid',gamma=0.001).fit(xtrain,ytrain)

In [59]:
print(accuracy_score(ytest,model1.predict(xtest)))
print(accuracy_score(ytest,model2.predict(xtest)))
print(accuracy_score(ytest,model3.predict(xtest)))

0.8
1.0
0.35384615384615387


In [60]:
params=[
    {'kernel':['linear'],'C':[1,10,100,1000]},
    {'kernel':['rbf'],'gamma':[1e-3,1e-4]},
    {'kernel':['sigmoid'],'gamma':[1e-3,1e-4],'C':[1,10,100,1000]},
    {'kernel':['poly'],'gamma':[1e-3,1e-4],'degree':[2,3,4]}
    ]

In [61]:
model=GridSearchCV(SVC(),params,cv=5)
model.fit(xtrain,ytrain)
model_best=model.best_estimator_
model_best.predict(xtest)

array([3, 2, 2, 1, 2, 7, 3, 2, 6, 1, 2, 7, 1, 2, 3, 7, 1, 2, 7, 2, 1, 2,
       5, 5, 2, 2, 2, 1, 2, 2, 5, 5, 2, 1, 5, 3, 7, 2, 6, 1, 2, 1, 7, 1,
       7, 1, 1, 1, 2, 1, 1, 3, 2, 7, 1, 1, 1, 2, 3, 7, 2, 3, 1, 1, 2],
      dtype=int64)

In [62]:
print("best kernel: ",model.best_estimator_.kernel)
print("best C: ",model.best_estimator_.C)
print("best accuracy: ",accuracy_score(ytest,ypred))

best kernel:  linear
best C:  1
best accuracy:  0.9846153846153847
